version: 2.1

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/command-convenience:0.1
    resource_class: xlarge
    steps:
      - checkout:
          path: project
