version: 2.1

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: docker:26.1.4
    resource_class: l1.2xlarge
    steps:
      - checkout:
          path: project
      - setup_remote_docker
