version: 2.1

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: docker:19.03.15
    resource_class: l1.xlarge
    steps:
      - checkout:
          path: project
      - setup_remote_docker
