version: 2.1

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    machine:
      image: ubuntu-2004:202008-01
    resource_class: arm.large
    steps:
      - checkout:
          path: project
