version: 2.1

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    macos:
      xcode: 13.3.1
    steps:
      - checkout:
          path: project
      - setup_remote_docker:
          version: 20.10.11
